(() => {
  const wait = ms => new Promise(r => setTimeout(r, ms));
  const norm = v => String(v ?? '').replace(/\s+/g, ' ').trim().toLowerCase();
  const visible = e => { if (!e || e.disabled) return false; const r = e.getBoundingClientRect(), s = getComputedStyle(e); return r.width > 0 && r.height > 0 && s.display !== 'none' && s.visibility !== 'hidden'; };
  const click = e => { if (!e || !visible(e)) return false; e.scrollIntoView?.({ block: 'center' }); e.click(); return true; };
  const dialog = () => [...document.querySelectorAll('.ui-dialog.add-passenger-dialog, .add-passenger-dialog.ui-dialog, [role="dialog"]')].find(visible);
  const setValue = (e, v) => { if (!e || v == null || v === '') return false; const proto = e instanceof HTMLInputElement ? HTMLInputElement.prototype : HTMLTextAreaElement.prototype; const setter = Object.getOwnPropertyDescriptor(proto, 'value')?.set; setter ? setter.call(e, String(v)) : e.value = String(v); ['input','change','blur'].forEach(t => e.dispatchEvent(new Event(t, { bubbles: true }))); return true; };
  const fieldByLabel = (root, text) => { const wanted = norm(text); return [...root.querySelectorAll('input, p-dropdown, [role="combobox"], .ui-dropdown')].find(e => { const box = e.parentElement?.parentElement || e.parentElement; return norm(box?.textContent).includes(wanted); }); };
  const choose = async (root, label, value) => { if (!value) return true; const f = root.querySelector(`[formcontrolname="${label}"]`) || fieldByLabel(root, label); if (!f) return false; if (f.matches('input')) return setValue(f, value); const trigger = f.querySelector('.ui-dropdown-trigger, .ui-dropdown-label-container, [role="combobox"]') || f; if (!click(trigger)) return false; for (let i=0;i<60;i++) { const item = [...document.querySelectorAll('li, [role="option"], .ui-dropdown-item')].find(x => visible(x) && norm(x.textContent) === norm(value)); if (item) { click(item); return true; } await wait(50); } return false; };
  const fill = async p => { const root = dialog(); if (!root) return null; const name = root.querySelector('[formcontrolname="passengerName"], input[placeholder*="Name" i], input[aria-label*="Name" i]'); const age = root.querySelector('[formcontrolname="passengerAge"], input[type="number"], input[placeholder*="Age" i]'); return { nameOk: setValue(name, p.name), ageOk: setValue(age, p.age), genderOk: await choose(root, 'passengerGender', p.gender), countryOk: await choose(root, 'passengerNationality', p.country || 'India'), preferenceOk: !p.preference || await choose(root, 'passengerBerthChoice', p.preference) }; };
  const optionText = text => { const w = norm(text); return [...document.querySelectorAll('label, span, p, div')].find(e => visible(e) && (norm(e.textContent) === w || (norm(e.textContent).includes(w) && norm(e.textContent).length < w.length + 80))); };
  const tick = async text => { const t = optionText(text); if (!t) return false; let n=t; for (let i=0;i<7 && n;i++,n=n.parentElement) { const input=n.querySelector?.('input[type="checkbox"]'); const role=n.querySelector?.('[role="checkbox"]'); const c=input || role; if (c) { if (!(c.checked || c.getAttribute('aria-checked') === 'true')) click(c); return true; } } return click(t.closest('label, [role="checkbox"], button') || t); };
  const applyPreferences = async p => { if (!p?.autoUpgrade && !p?.confirmedBerths) return true; for (let i=0;i<30;i++) { const a = optionText('Consider for Auto Upgradation'), b = optionText('Book only if confirm berths are allotted'); if (a || b) break; const h = optionText('Other Preferences'); if (h) click(h.closest('button, [role="button"], .accordion-header') || h); await wait(100); } return (!p.autoUpgrade || await tick('Consider for Auto Upgradation')) && (!p.confirmedBerths || await tick('Book only if confirm berths are allotted')); };
  chrome.runtime.onMessage.addListener((m, s, reply) => { if (!['fillPassengers','selectExistingPassengers'].includes(m.action)) return; (async()=>{ if(m.action==='selectExistingPassengers'){reply({message:'Select existing passengers manually from the IRCTC list.'});return;} const list=Array.isArray(m.passengers)?m.passengers:[]; let done=0; for(const p of list){const b=[...document.querySelectorAll('button.btn-new-passenger, button')].find(e=>visible(e)&&norm(e.textContent).includes('new passenger')); if(!click(b)) break; for(let i=0;i<40&&!dialog();i++) await wait(50); const r=await fill(p); if(!r||!r.nameOk||!r.ageOk||!r.genderOk||!r.countryOk||!r.preferenceOk){reply({message:`Passenger ${done+1} could not be completed. Check: ${!r?.nameOk?'Name, ':''}${!r?.ageOk?'Age, ':''}${!r?.genderOk?'Gender, ':''}${!r?.countryOk?'Country, ':''}${!r?.preferenceOk?'Preference':''}`});return;} const add=[...document.querySelectorAll('button')].find(e=>visible(e)&&/add passenger|save passenger/i.test(e.textContent)); if(!click(add)) break; await wait(500); done++;} if(done===list.length){const ok=await applyPreferences(m.preferences); reply({message:`Added and filled ${done} passenger(s). ${ok?'Requested preferences selected.':'Please check the requested preferences manually.'}`});}else reply({message:`Filled ${done} of ${list.length} passenger(s).`}); })(); return true; });
})();
