(() => {
  const normalize = value => String(value ?? "").toLowerCase().replace(/[^a-z0-9]/g, "");
  const visible = element => { if (!element || element.disabled) return false; const rect = element.getBoundingClientRect(); const style = getComputedStyle(element); return rect.width > 0 && rect.height > 0 && style.visibility !== "hidden" && style.display !== "none"; };
  const fields = root => [...(root || document).querySelectorAll("input, select, textarea, [role='combobox'], [aria-haspopup='listbox'], mat-select")].filter(visible);
  const textFor = element => { const values = []; if (element.labels) [...element.labels].forEach(label => values.push(label.innerText)); ["aria-label", "aria-labelledby", "placeholder", "name", "id", "formcontrolname"].forEach(attribute => { const value = element.getAttribute(attribute); if (value) values.push(value); }); const parent = element.closest("div, td, li, tr, section"); if (parent?.innerText) values.push(parent.innerText.slice(0, 240)); return normalize(values.join(" ")); };
  const setValue = (element, value) => { if (!element || value === undefined || value === null || value === "") return false; const prototype = element instanceof HTMLTextAreaElement ? HTMLTextAreaElement.prototype : element instanceof HTMLInputElement ? HTMLInputElement.prototype : null; const setter = prototype && Object.getOwnPropertyDescriptor(prototype, "value")?.set; if (setter) setter.call(element, String(value)); else element.value = String(value); ["input", "change", "blur"].forEach(type => element.dispatchEvent(new Event(type, { bubbles: true, composed: true }))); return true; };
  const best = (available, keywords, used) => { let selected = null; let score = 0; for (const element of available) { if (used.has(element)) continue; const label = textFor(element); const current = keywords.reduce((total, keyword) => total + (label.includes(normalize(keyword)) ? 1 : 0), 0); if (current > score) { selected = element; score = current; } } if (selected) used.add(selected); return selected; };
  const fillGeneralDetails = details => { const available = fields(document); const used = new Set(); let count = 0; const mappings = [[["email", "email id", "email address"], "email"], [["city"], "city"], [["state"], "state"], [["country"], "country"], [["pincode", "pin code", "postal code", "zip code", "zipcode"], "pincode"], [["gothram", "gotram", "gothra"], "gothram"]]; for (const [keywords, key] of mappings) if (setValue(best(available, keywords, used), details?.[key])) count++; return count; };
  const fillPilgrim = (root, pilgrim) => { const available = fields(root); const used = new Set(); let count = 0; if (setValue(best(available, ["pilgrim name", "devotee name", "full name", "name"], used), pilgrim.name)) count++; if (setValue(best(available, ["age", "years"], used), pilgrim.age)) count++; if (setValue(best(available, ["gender", "sex"], used), pilgrim.gender)) count++; if (setValue(best(available, ["photo id proof", "id proof", "proof type", "document type", "identity proof"], used), pilgrim.idType)) count++; if (setValue(best(available, ["photo id number", "id number", "proof id number", "document number", "identity number"], used), pilgrim.idNumber)) count++; return count; };
  const findGroups = expected => { const all = fields(document); if (!expected) return []; const candidates = [...document.querySelectorAll("fieldset, section, article, li, tr, .row, [class*='pilgrim'], [class*='passenger'], [class*='devotee']")].filter(visible).filter(group => fields(group).length >= 3); const unique = []; for (const group of candidates) { if (!unique.some(existing => existing.contains(group))) unique.push(group); if (unique.length >= expected) break; } if (unique.length >= expected) return unique; const chunkSize = Math.max(1, Math.floor(all.length / expected)); return Array.from({ length: expected }, (_, index) => ({ querySelectorAll: () => all.slice(index * chunkSize, index === expected - 1 ? all.length : (index + 1) * chunkSize) })); };
  chrome.runtime.onMessage.addListener((message, sender, sendResponse) => { if (message.action !== "fill") return; try { const pilgrims = Array.isArray(message.profile?.pilgrims) ? message.profile.pilgrims : []; let filled = fillGeneralDetails(message.profile?.generalDetails || {}); const groups = findGroups(pilgrims.length); pilgrims.forEach((pilgrim, index) => { filled += fillPilgrim(groups[index] || document, pilgrim); }); sendResponse({ message: filled ? `Filled ${filled} field(s), including general details. Review all details before continuing.` : "No matching fields found. Check the page and form fields." }); } catch (error) { console.error("TTD Smart Autofill:", error); sendResponse({ message: "Could not fill this page. Please review manually." }); } return true; });
})();
